from(bucket: "telemetria_birra")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "fermentador")
  |> filter(fn: (r) => int(v: v.timeRangeStop) - int(v: r._time) <= 900000000000)
  |> filter(fn: (r) => r._field == "message_seq" or r._field == "setpoint" or r._field == "setpoint_applied")
  |> map(fn: (r) => ({r with _value: string(v: r._value)}))
  |> group(columns: ["_measurement"])
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  |> limit(n: 1)
  |> filter(fn: (r) => exists r.setpoint_applied or exists r.setpoint)
  |> map(fn: (r) => ({_time: r._time, _field: "Aplicada", _value: float(v: if exists r.setpoint_applied then r.setpoint_applied else r.setpoint)}))
