from(bucket: "telemetria_birra")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "fermentador")
  |> filter(fn: (r) => r._field == "setpoint_applied" or r._field == "setpoint")
  |> group(columns: ["_measurement", "_start", "_stop"])
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> map(fn: (r) => ({_start: r._start, _stop: r._stop, _time: r._time, _field: "Consigna aplicada", _value: float(v: if exists r.setpoint_applied then r.setpoint_applied else r.setpoint)}))
  |> group(columns: ["_field"])
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
