from(bucket: "telemetria_birra")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "fermentador")
  |> filter(fn: (r) => int(v: v.timeRangeStop) - int(v: r._time) <= 900000000000)
  |> filter(fn: (r) => r._field == "controller_state" or r._field == "message_seq")
  |> map(fn: (r) => ({r with _value: string(v: r._value)}))
  |> group(columns: ["_measurement"])
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  |> limit(n: 1)
  |> filter(fn: (r) => exists r.controller_state)
  |> map(fn: (r) => ({_time: r._time, _field: "Controlador", _value: r.controller_state}))
