from(bucket: "telemetria_birra")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "fermentador")
  |> filter(fn: (r) => int(v: v.timeRangeStop) - int(v: r._time) <= 900000000000)
  |> filter(fn: (r) => r._field == "message_seq" or r._field == "mosto" or r._field == "mosto_valid")
  |> map(fn: (r) => ({r with _value: string(v: r._value)}))
  |> group(columns: ["_measurement"])
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  |> limit(n: 1)
  |> filter(fn: (r) => exists r.mosto and float(v: r.mosto) >= -5.0 and float(v: r.mosto) <= 40.0 and (if exists r.mosto_valid then r.mosto_valid == "true" else true))
  |> map(fn: (r) => ({_time: r._time, _field: "MOSTO", _value: float(v: r.mosto)}))
